In [1]:
# Import dependencies
import pandas as pd

In [2]:
filepath = '../Resources/ratings_and_sentiments.csv'
# Read file into DataFrame
ilovecoffee_df = pd.read_csv(filepath)
ilovecoffee_df.head()

,coffee_shop_name,review_text,rating,num_rating,cat_rating,bool_HIGH,overall_sent,vibe_sent,tea_sent,service_sent,seating_sent,price_sent,parking_sent,location_sent,alcohol_sent,coffee_sent,food_sent,hours_sent,internet_sent,local_sent
0,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,3,0,0,0,0,0,0,1,3,0,0.0,0,0
1,The Factory - Cafe With a Soul,"12/2/2016 Listed in Date Night: Austin, vibe i...",4.0 star rating,4,HIGH,1,3,3,0,0,0,0,0,0,0,0,2,0.0,0,0
2,The Factory - Cafe With a Soul,11/30/2016 1 check-in Listed in food seating I...,4.0 star rating,4,HIGH,1,2,2,0,0,3,0,0,0,0,-1,2,0.0,0,0
3,The Factory - Cafe With a Soul,11/25/2016 Very cool vibe! Good drinks Nice se...,2.0 star rating,2,LOW,0,1,0,0,0,-1,-1,0,0,0,0,0,0.0,0,0
4,The Factory - Cafe With a Soul,12/3/2016 1 check-in They are location within ...,4.0 star rating,4,HIGH,1,2,0,0,0,0,0,3,0,0,0,0,0.0,0,0

In [3]:
# Find all reviews with a number rating greater than or equal to 4.
ilovecoffee_df[ilovecoffee_df['num_rating'] >= 4].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6140 entries, 0 to 7615
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   coffee_shop_name  6140 non-null   object
 1   review_text       6140 non-null   object
 2   rating            6140 non-null   object
 3   num_rating        6140 non-null   int64
 4   cat_rating        6140 non-null   object
 5   bool_HIGH         6140 non-null   int64
 6   overall_sent      6140 non-null   int64
 7   vibe_sent         3755 non-null   object
 8   tea_sent          6140 non-null   int64
 9   service_sent      6140 non-null   int64
 10  seating_sent      6140 non-null   int64
 11  price_sent        6140 non-null   int64
 12  parking_sent      6140 non-null   object
 13  location_sent     6140 non-null   int64
 14  alcohol_sent      6140 non-null   int64
 15  coffee_sent       6140 non-null   object
 16  food_sent         6140 non-null   object
 17  hours_sent        6139 non-null   float64
 18  internet_sent     6140 non-null   int64
 19  local_sent        6140 non-null   int64
dtypes: float64(1), int64(11), object(8)
memory usage: 1007.3+ KB

In [4]:
# Find all the coffee shops with a overall sentiment greater than or equal to 4.
ilovecoffee_df[ilovecoffee_df['overall_sent'] >= 4]

,coffee_shop_name,review_text,rating,num_rating,cat_rating,bool_HIGH,overall_sent,vibe_sent,tea_sent,service_sent,seating_sent,price_sent,parking_sent,location_sent,alcohol_sent,coffee_sent,food_sent,hours_sent,internet_sent,local_sent
0,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,3,0,0,0,0,0,0,1,3,0,0.0,0,0
233,Mozart's Coffee Roasters,9/21/2016 1 check-in Scenery 10/10. Coffee 10/...,5.0 star rating,5,HIGH,1,4,0,0,0,0,-1,0,0,0,1,0,0.0,0,0
931,Venezia Italian Gelato,6/19/2016 After sampling several food places a...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,0,0,0.0,0,0
1101,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,4,0,0,0,0,0,0,0,0,0,0.0,0,0
1466,Figure 8 Coffee Purveyors,11/28/2016 2 check-ins Really excellent coffee...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,4,0,0.0,0,0
1591,MaГ±ana Coffee & Juice,"5/30/2016 Manana was brand new to me, just wen...",5.0 star rating,5,HIGH,1,4,4,0,0,0,0,0,0,0,3,0,0.0,0,0
2008,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,4,0,0,0,0,0,0,0,0,0,0.0,0,0
2213,Flat Track Coffee,12/28/2013 Wow. Wow. Best coffee In Austin...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,1,0,0.0,0,0
2595,Flightpath Coffeehouse,8/13/2015 Digital Nomad Cafe Score - 5/5 seat...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,0,0,0.0,0,0
2681,Third Coast Coffee Roasting Company,8/22/2009 I've never visited the store. Howeve...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,4,0,0.0,0,0
2831,Dolce Neve,3/27/2016 If you like a creamy consistency wit...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,0,0,0.0,0,0
3051,Halcyon,3/3/2015 1 check-in Listed in Pretending to Ho...,4.0 star rating,4,HIGH,1,4,4,0,0,0,0,0,0,0,1,0,0.0,0,0
3106,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,4,0,0,0,0,0,0,0,0,0,0.0,0,0
3390,Arturo's Underground Cafe,9/24/2016 Great food. Haven't had creative foo...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,0,4,0.0,0,0
3425,Arturo's Underground Cafe,4/17/2016 Absolutely loved this place! We got ...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,0,2,0.0,0,0
3787,Lucky Lab Coffee,7/31/2015 I absolutely loved Lucky Lab Coffee ...,5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,1,0,0.0,0,0
4137,Halcyon,3/3/2015 1 check-in Listed in Pretending to Ho...,4.0 star rating,4,HIGH,1,4,4,0,0,0,0,0,0,0,1,0,0.0,0,0
4419,Tea Haus,"12/2/2016 Love this place, mint mojito iced co...",5.0 star rating,5,HIGH,1,4,0,0,0,0,0,0,0,0,4,0,0.0,0,0
4515,Friends & Neighbors,5/17/2015 Amazing amazing!! Inspiring! What's ...,5.0 star rating,5,HIGH,1,4,NaN,0,2,2,0,0,0,0,0,0,0.0,0,0
4530,Sorrento's Coffee,5/24/2016 1 check-in Stopped in here the other...,5.0 star rating,5,HIGH,1,4,NaN,0,0,0,0,0,0,0,1,4,0.0,0,0
4576,Sorrento's Coffee,11/23/2014 1 check-in I was in the area and ha...,4.0 star rating,4,HIGH,1,4,NaN,0,0,0,0,0,0,0,1,0,0.0,0,0
4771,Venezia Italian Gelato,6/19/2016 After sampling several food places a...,5.0 star rating,5,HIGH,1,4,NaN,0,0,0,0,0,0,0,0,0,0.0,0,0
5086,Halcyon,3/3/2015 1 check-in Listed in Pretending to Ho...,4.0 star rating,4,HIGH,1,4,NaN,0,0,0,0,0,0,0,1,0,0.0,0,0
5612,Dominican Joe,2/3/2014 1 check-in Two Words: Flan coffee. O...,5.0 star rating,5,HIGH,1,4,NaN,0,0,0,0,0,0,0,1,0,0.0,0,0
5998,La Tazza Fresca,11/12/2013 1 check-in This cafe is a regular s...,4.0 star rating,4,HIGH,1,4,NaN,0,0,0,2,0,0,0,0,0,0.0,0,0
6428,"Strange Brew, Austin Coffee",10/29/2014 1 check-in I really loved this plac...,5.0 star rating,5,HIGH,1,4,NaN,0,0,1,0,0,0,0,0,0,0.0,0,0
6836,Teo,10/27/2014 1 check-in This place has excellent...,5.0 star rating,5,HIGH,1,4,NaN,0,1,0,0,0,0,0,0,4,0.0,0,0
6963,La Patisserie,4/3/2014 1 check-in This little sweet shop was...,4.0 star rating,4,HIGH,1,4,NaN,0,0,0,0,4,0,0,0,0,0.0,0,0
6999,My Sweet Austin,4/23/2014 I absolutely loved my bridal food! I...,5.0 star rating,5,HIGH,1,4,NaN,0,0,0,0,0,0,0,0,4,0.0,0,0
7099,Cafe Java,9/28/2016 A co-worker suggested Cafe Java and ...,4.0 star rating,4,HIGH,1,4,NaN,0,2,0,1,0,0,0,0,1,0.0,0,0
7148,Russell's Bakery,5/15/2016 Coconut food is Awesome! Best I have...,5.0 star rating,5,HIGH,1,4,NaN,0,0,0,0,0,0,0,0,0,0.0,0,0
7558,The Steeping Room,10/18/2015 OMG! Try the Chai Spiced French foo...,4.0 star rating,4,HIGH,1,4,NaN,0,0,0,0,0,0,0,0,1,0.0,0,0

In [5]:
# Return the count of the above query.
best_coffee_shop = ilovecoffee_df[(ilovecoffee_df['num_rating'] >= 4) & (ilovecoffee_df['overall_sent'] >= 4)]
print("There are {} coffee shops which are the best.".format(len(best_coffee_shop)))

There are 32 coffee shops which are the best.

In [6]:
# Change the name of the review_text column to review
ilovecoffee_df = ilovecoffee_df.rename(columns={"review_text": "review"})
ilovecoffee_df.head()

,coffee_shop_name,review,rating,num_rating,cat_rating,bool_HIGH,overall_sent,vibe_sent,tea_sent,service_sent,seating_sent,price_sent,parking_sent,location_sent,alcohol_sent,coffee_sent,food_sent,hours_sent,internet_sent,local_sent
0,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,3,0,0,0,0,0,0,1,3,0,0.0,0,0
1,The Factory - Cafe With a Soul,"12/2/2016 Listed in Date Night: Austin, vibe i...",4.0 star rating,4,HIGH,1,3,3,0,0,0,0,0,0,0,0,2,0.0,0,0
2,The Factory - Cafe With a Soul,11/30/2016 1 check-in Listed in food seating I...,4.0 star rating,4,HIGH,1,2,2,0,0,3,0,0,0,0,-1,2,0.0,0,0
3,The Factory - Cafe With a Soul,11/25/2016 Very cool vibe! Good drinks Nice se...,2.0 star rating,2,LOW,0,1,0,0,0,-1,-1,0,0,0,0,0,0.0,0,0
4,The Factory - Cafe With a Soul,12/3/2016 1 check-in They are location within ...,4.0 star rating,4,HIGH,1,2,0,0,0,0,0,3,0,0,0,0,0.0,0,0

In [7]:
# Change the name of the bool_HIGH column to bool_high
ilovecoffee_df = ilovecoffee_df.rename(columns={"bool_HIGH": "bool_high"})
ilovecoffee_df.head()

,coffee_shop_name,review,rating,num_rating,cat_rating,bool_high,overall_sent,vibe_sent,tea_sent,service_sent,seating_sent,price_sent,parking_sent,location_sent,alcohol_sent,coffee_sent,food_sent,hours_sent,internet_sent,local_sent
0,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,3,0,0,0,0,0,0,1,3,0,0.0,0,0
1,The Factory - Cafe With a Soul,"12/2/2016 Listed in Date Night: Austin, vibe i...",4.0 star rating,4,HIGH,1,3,3,0,0,0,0,0,0,0,0,2,0.0,0,0
2,The Factory - Cafe With a Soul,11/30/2016 1 check-in Listed in food seating I...,4.0 star rating,4,HIGH,1,2,2,0,0,3,0,0,0,0,-1,2,0.0,0,0
3,The Factory - Cafe With a Soul,11/25/2016 Very cool vibe! Good drinks Nice se...,2.0 star rating,2,LOW,0,1,0,0,0,-1,-1,0,0,0,0,0,0.0,0,0
4,The Factory - Cafe With a Soul,12/3/2016 1 check-in They are location within ...,4.0 star rating,4,HIGH,1,2,0,0,0,0,0,3,0,0,0,0,0.0,0,0

In [8]:
# Save your changes to the file as a pipe delimited file.
ilovecoffee_df.to_csv('yelp_rating_with_pipe.csv', sep='|')